# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
flute = Instrument.create({ name: "Flute", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZobirtApnM7_uzxgQj-YL8JJTBuKxclsryrN8UcuE90yLTQucOQ"})
percussion = Instrument.create({ name: "Percussion", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjbtB09bLnL-88q50uWWZ4PLU-8p2RoCfu0S9C1jwNJ3V1Te6w"})
trombone = Instrument.create({ name: "Trombone", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8lksz2LjicsCPasHDgPGzG6JI98AHQhiBHyBofu9u5L0wgYXCyg"})
voice = Instrument.create({ name: "Voice", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRm2T4Kcq1MIZzYLcbF0o7IuJGIt_BbwtvukF2MzkcYAu6H7hGm"})
oboe = Instrument.create({name: "Oboe", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeOIHr8Ya7bU_5swd9_1-clmJK4AIcAXnxRwW4z-e9DunloKo8NA"})
saxophone = Instrument.create({ name: "Saxophone", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyHHF9fxFUB12p41E4qtBw1GTDq2xQVvl9vSsoOx-CqQZNyDZwCg"})
bassoon = Instrument.create({ name: "Bassoon", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXntiaYfk3Di7qtKinQbgIsfyvgDQp99AiZQEpyhq0i9yUfRv0eg"})
clarinet = Instrument.create({ name: "Clarinet", picture: "https://www.musicnexo.com/blog/wp-content/uploads/2017/03/clarinet-86157_1920-1200x800.jpg"})
trumpet = Instrument.create({ name: "Trumpet", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvfL6z-nM_260-X-amQynaC02ugIMyZR1w1EBesnilFUFBewmeeA"})
horn = Instrument.create({ name: "Horn", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAcjcI-0dOCqn6sRqXPIG5VU4i1PL6GspFxZdzRfl2UKjafjK5Xg"})
tuba = Instrument.create({ name: "Tuba", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-QBr6OR07ODFSsymc4FYAD8reQMCpAdRCi5BgIEoTBlFiBZWtTA"})
guitar = Instrument.create({ name: "Guitar", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRULxe69CK-B--4fwZ9BsETfuxsO09XeeY9tJiKDEY681Q1K3Up2w"})
violin = Instrument.create({ name: "Violin", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9duMrYJ6JxKn_nwhqYfK4DZjDWh8vWvWyE9jb1eM1uFaYzjFN"})
cello = Instrument.create({ name: "Cello", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNogKTJxksq1_V4yt76U29xK5jPb5QQ08iHZZ8J-krt1sQJ9E"})
bass = Instrument.create({ name: "Bass", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNYI84IEB478PEIUdM5qYbmZlP1zFCUz177cg3itvV2a7KrDPWg"})
piano = Instrument.create({ name: "Piano", picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStlq2TFADjqvoB0k0ttm40FoeEp3am-r4z92DC7DEsesqJ-H9M"})

alan = User.create({ calendar: "https://calendar.google.com/calendar/embed?src=1k07fk080vafvmh9h3t0u2pim4%40group.calendar.google.com&ctz=America%2FNew_York", long_bio: "Alan Dust currently serves as the Director of Fine Arts in the Windham School District, a position he has held since July 2016. As Director of Fine Arts, Alan oversees the K-12 Music, Visual Arts, Family and Consumer Sciences, and Technical Arts Departments in the Windham School District. In addition to this, he is also the Director of the Concert Band and Honors Winds Ensembles.

Prior to Windham, Alan began his career in Ithaca, NY at Ithaca College, where he taught the Percussion Methods Courses as a part of his assistantship for his Master’s program. In 2008, he moved to Wisconsin, where was the director of bands at Shorewood Intermediate School and assisted with the high school marching and pep bands. In 2009, Alan was appointed Director of Instrumental Music for the Northern Ozaukee School District, where he oversaw the entire 5-12 instrumental music program. In 2011, Alan became the Director of Bands for Port Washington High School, where he spent a total of five years directing two concert bands, one curricular jazz ensemble, AP Music Theory, Pep Band, Marching Band, 16 various chamber ensembles, and private lessons. During his time in Wisconsin, Alan toured with various ensembles around Wisconsin and various other venues throughout locations such as Chicago, St. Louis, Memphis, New Orleans, Florida, and Italy.

Alan has been an active member in the Wisconsin Music Educators Association (WMEA), National Association for Music Education (NAfME), and is currently also a member of the New Hampshire Music Educators Association (NHMEA). In consecutive years, Alan received the honor of “Top 10” teacher in his district multiple times, an award of which he was nominated by students. In 2016, Alan was nominated by various parents, students, colleagues, and administration for an Herb Kohl Teacher Fellowship Award. Throughout his time in Wisconsin, Alan guest conducted the Central Lakeshore Honors Band, the Air Force Band of Mid America, and at various other schools in the Southeast Wisconsin Area. He has collaborated with many professional musicians, composers, and college professors to work with his students individually, in small groups, for master classes, and collaborate through performances. In 2011, Alan spoke at the International Midwest Band and Orchestra Clinic about his professional experiences for Dr. Elizabeth Peterson’s presentation on her new book, “The Music Teacher’s First Year.”

Alan Graduated Cum Laude from Ithaca College with a Bachelor of Music degree in Music Education with a concentration in Percussion. In 2008, he received his Master of Music degree in Music Performance with a concentration in Percussion. During this time, he also guest conducted the Ithaca College Campus Band, Percussion Ensembles, Brass Choir, and was an assistant for the Music Technology and Music Field Experience courses. Alan has also completed various coursework at Cardinal Stritch University and the University of New Hampshire towards the degree of Master of Science in Educational Leadership and towards a Certificate in Curriculum and Instruction.", email: "alan.dust@gmail.com", encrypted_password: "123456", first_name: "Alan", last_name: "Dust", age: 34, role: "teacher", zip: "01852", short_bio: "I have taught band at all levels for 12 years.  I am primarily a percussionist, but can teach all instruments.", lesson_location: "Lowell, MA", password: "123456", remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/1/alan.jpg"})

patricia = User.create({ calendar: "https://calendar.google.com/calendar/embed?src=phtuejrgr2o3h7s5fp9rjptkuc%40group.calendar.google.com&ctz=America%2FNew_York", email: "patricia.deandres@gmail.com", encrypted_password: "123456", first_name: "Patricia", last_name: "DeAndres", age: 33, role: "teacher", zip: "01852", short_bio: "I am a professional flutist.  I currently perform with the Metropolitan Wind Symphony and have performed with Symphony Orchestras across Europe.", lesson_location: "Lowell, MA", password: "123456", remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/2/patri.jpg", long_bio: "She started her musical studies in the professional conservatory Arturo Soria in Madrid, Spain, being graduated with Award of Extraordinary Skill and Excellence. After that she continued studying at the Royal Conservatory of Music in Madrid, Spain with the professor Manuel Guerrero obtaining her masters degree in 2012. She has attended masterclasses with well renowned flutists such a Antonio Arias and Miguel Ángel Angulo  (National Orchestra of Spain), Aurèle Nicolet (Berlin Philharmonic) and Stefán R. Höskuldsson  (MET Orchestra and Chicago Symphony orchestra), among others. As an orchestra and chamber music performer she was awarded with Acordes Caja Madrid Award in 2008 and the 1st Prize in First Section of International Music Competition Ciudad de Valencia in 2010 She has performed as a soloist in the National Music Hall of Spain and as orchestra player in the Music Palace of Valencia as well as the most important music halls in Spain. As a chamber music player she was invited to perform in the Stenway Series with pianist Roberto Berrocal, Lowell Folk Festival with flutist Geraldine Morillo and has collaborated for miscellaneous projects by musicians of the Boston Symphony and Boston Pops. She has been invited to perform with the Metropolitan Wind Symphony. Patricia has also a bachelor degree in History of Art, a postgraduate diploma in Curation of Heritage by for the Autonoma University of Madrid and have been part of the management staff in the Prado Museum in Madrid, Spain. She has worked for Arista Flutes as an office manager, brand ambassador and flute maker, making professional-level handmade flutes and headjoints in silver, gold and platinum. Since April 2017 she works for Powell Flutes as a key stringer, activity that she combines with performing and teaching. "})

mark = User.create({ email: "mark.taddonio@gmail.com", encrypted_password: "123456", first_name: "Mark", last_name: "Taddonio", age: 25, role: "teacher", zip: "03087", short_bio: "I am the current band director at Windham High School.  I am primarily a trombonist, but can teach all wind and brass instruments as well as voice.  I have been teaching professionally for five years and am excited to have you as a student!", lesson_location: "Windham, NH", password: "123456", remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/3/mark.jpg", long_bio: "Mark Taddonio has been with the Windham School District since 2015, initially as an Associate Director of Bands, and now as the Director of Bands at Windham High School. Mark oversees the Concert Band, Pep Band, Honors Jazz Ensemble, and Honors Windham Ensemble. Additionally, he teaches AP Music Theory and Guitar. Mark is a graduate of the University of New Hampshire where he earned his Bachelor of Music Education, cum laude. During this time he studied jazz and classical trombone while taking part in many different performing ensembles in addition to courses in music, pedagogy, education, and philosophy.  Mark is a very active freelance musician across New Hampshire and northern Massachusetts. He can be regularly heard playing with the Tall Granite Big Band, the Pocket Big Band, the Scott Spradling Band, Gretchen and the Pickpockets, as well as various pit orchestra and chamber groups. A brass specialist, he occasionally performs on euphonium, bass trombone, French horn, and trumpet."})

sheila = User.create({ remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/4/sheila.jpg", email: "sheila.cuneo@gmail.com", encrypted_password: "123456", first_name: "Sheila", last_name: "Cuneo", age: 50, role: "teacher", zip: "03087", short_bio: "I am the current choir director at Windham High School.  I am primarily a vocalist and teach all voices.", lesson_location: "Windham, NH", password: "123456", long_bio: "Sheila Cuneo has been teaching music for the past thirteen years in the Windham School District. She began teaching at the Windham Middle School as the chorus director and music appreciation instructor. She was also the director for the Select Choir. During her tenure at the Middle School, she also directed four musicals and was the vocal coach for most of the musical productions throughout her time there. In 2012, Sheila moved to the High School where she is currently the Director of Choirs and teacher for all the music electives, including guitar, piano, music and media, percussion and music theory. She has also been vocal coach for the musicals, including the Phantom of the Opera, which was the production the year before she joined the staff at Windham High School. Since then she has enjoyed working closely with the drama director in both rehearsal and performance. The WHS Choir has had the opportunity to travel to New York where the students participated in a workshop with Dr. Cindy Bell from Hofstra University. We continued on into New York City where students were part of a Broadway workshop with Broadway actor and singer, Jason Forbach who later performed in a lead roll of Les Miserables. Currently, the WHS choir is planning an exciting trip to Canada where they will perform for the Mayor of Quebec and the Governor of Montreal. They will also have a special performance in the Basilica De Notre Dame in Quebec. Outside of Sheilas teaching responsibilities, she has been a member of several different community and church choirs throughout the state performing as both soloist and choral director. She has also taught both flute and voice privately. In 2004, she had the opportunity to perform with the St. Annes Choir of Hampstead by special invitation at a High Mass in the Vatican City, Rome. She also performed as soloist in the Santa Maria Church, Rome, Italy during that same trip. She has also coached several students who have earned their way into both Jazz and Classical All-State Festivals."})

billy = User.create({email: "billy.chou@gmail.com", encrypted_password: "123456", first_name: "Billy", last_name: "Chou", age: 34, role: "teacher", zip: "22032", short_bio: "I have been playing piano since I was 3 years old.  I accept piano students of all levels.  Come and see how much fun learning piano can be by taking private lessons! I also teach mallet percussion!", lesson_location: "Fairfax, VA", password: "123456", remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/5/billy.jpeg"})

steve = User.create({email: "steve.peterson@gmail.com", encrypted_password: "123456", first_name: "Stephen", last_name: "Peterson", age: 58, role: "teacher", zip: "61821", short_bio: "I am the director of bands at the University of Illinois.  I teach any and all instruments privately.  Please let me know if you want to learn your instrument seriously at a high level!  I am accepting advanced students of all wind and brass instruments.", lesson_location: "Urbana, IL", password: "123456", remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/1/Alan.jpg",
long_bio: "Dr. Stephen G. Peterson was appointed Director of Bands at the University of Illinois in the fall of 2015. As Director of Bands, he conducts the Wind Symphony, leads the graduate wind conducting program, teaches courses in wind literature, and guides all aspects of one of the nation’s oldest, largest, and most storied band programs. Prior to joining the faculty at the University of Illinois he served as Director of Bands at Ithaca College in Ithaca, New York, for seventeen years. From 1988-1998 he served as Associate Director of Bands at Northwestern University in Evanston, Illinois. Dr. Peterson was also conductor of the renowned Northshore Concert Band. He held positions as Associate and Interim Director of Bands at Stephen F. Austin State University in Nacogdoches, Texas and has several years of successful teaching experience in the public schools in Arizona.  Dr. Peterson maintains a busy schedule as a conductor and clinician, and as such, has appeared on four continents and in forty-two states. He is a member of the National Association for Music Education, the College Band Directors National Association, the World Association of Symphonic Bands and Ensembles, the Illinois Music Educators Association, and has been honored with membership in the prestigious American Bandmasters Association. He is also member of Phi Mu Alpha, Phi Kappa Phi, Pi Kappa Lambda, and an honorary member of Tau Beta Sigma, and Kappa Kappa Psi. He is past president of the College Band Directors National Association.  Dr. Peterson was the first to receive the Doctor of Music degree in wind conducting from Northwestern University and earned Master’s and Bachelor’s degrees from Arizona State University. In 2012 he was awarded the prestigious Ithaca College Faculty Excellence Award, recognizing his contributions to Ithaca College. His ensembles have appeared before national conventions of the American Bandmasters Association, the College Band Directors National Association, the National Association of College Wind and Percussion Instructors, the American School Band Directors Association, at Orchestra Hall with the Chicago Symphony Chorus, and at Lincoln Center."})

chris = User.create({email: "chris.neske@gmail.com", encrypted_password: "123456", first_name: "Christopher", last_name: "Neske", age: 34, role: "teacher", zip: "11730", short_bio: "I am a high school band director in East Islip, NY.  I am currently accepting students of all levels and all instruments, winds and brass.  Please message me if you want to level up on your instrument!", lesson_location: "East Islip, NY", password: "123456", remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/7/chris.jpeg"})

gordon = User.create({email: "Gordon.Stout@gmail.com", encrypted_password: "123456", first_name: "Gordon", last_name: "Stout", age: 66, role: "teacher", zip: "14850", short_bio: "I have been teaching percussion for almost 40 years.  I am still thrilled to accept new students and would love to have you join my private lesson studio.  Please contact me for more information!  I look forward to working with you!", lesson_location: "Ithaca, NY", password: "123456", remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/8/gordon.jpeg",
long_bio: "GORDON STOUT (b.1952) is currently Professor of Percussion at the School of Music, Ithaca College, Ithaca, N.Y., where he has taught percussion since 1980. A composer as well as percussionist who specializes on marimba, he has studied composition with Joseph Schwantner, Samuel Adler and Warren Benson, and percussion with James Salmon and John Beck.
Many of his compositions for marimba are published, and have already become standard repertoire for marimbists world-wide (www.mostlymarimba.com). A frequent lecture-recitalist for the Percussive Arts Society, he has appeared at more than a dozen  International PAS Conventions to date as featured marimbist, as well as throughout the United States and Canada, Europe, Japan, Taiwan, Thailand, Singapore, Hungary, Bulgaria, Mexico, Denmark, Puerto Rico, Italy, Greece, and Spain. In May of 1983 he performed clinics and recitals in France, Germany, Holland and Belgium with transcendental virtuosity being described as the Rubinstein of all aspects of the marimba.
Gordon has been on the Jury of seven different international marimba competitions. On new years day in 2006 he conducted a 100 person marimba orchestra in the National Concert Hall in Taipei, Taiwan as part of the Taiwan International Percussion Convention. His composition New York Triptych for marimba orchestra, was commissioned by and written for the 50th anniversary celebration of the Percussive Arts Society, premiered at PASIC 2011 in Indianapolis, IN.  He has also conducted marimba orchestras in Australia, Croatia,  and throughout the United States.  Most recently he conducted a marimba orchestra of 75 persons on 120 marimbas at Kutztown University in PA in November of 2015.
Gordon was inducted into the Percussive Arts Society Hall of Fame in November of 2012. Gordon Stout is represented by the Percussion Events Registry Company, and owns and plays a marimba manufactured by DeMorrow Instruments (www.demorrowinstruments.com). He is the creator of Young Composers International (www.youngcomposersinternational.com), a service dedicated to disseminating new and interesting works for marimba and percussion written by young composers from around the world."})

fonder = User.create({email: "Mark.Fonder@gmail.com", encrypted_password: "123456", first_name: "Mark", last_name: "Fonder", age: 65, role: "teacher", zip: "54911", short_bio: "I have been teaching band for over 35 years.  I am proficient in all wind and brass instruments, with trombone being my forte.  I am happy to accept students at all levels and all instruments.  Please contact me for more information!", lesson_location: "Appleton, WI", password: "123456", remote_profile_photo_url: "https://s3.amazonaws.com/duet-production/uploads/user/profile_photo/9/fonder.jpeg",
long_bio: "Mark Fonder taught fulltime instrumental music and band from elementary school through college for over 35 years.  As professor of music, he was the conductor of the Ithaca College Concert Band and taught instrumental music education courses at Ithaca College from 1989 until his retirement in 2015.  From 1994 to 2003, he was the Chairman of their Music Education Department and in 2017 was named Professor Emeritus.  He is still active as a guest conductor, adjudicator, school music consultant, and clinician and serves in these capacities throughout the United States.  Internationally, he has guest conducted, given research presentations or adjudicated bands in Australia, Japan, Canada, China, Malaysia, Singapore, Taiwan, throughout the Euro zone and the United Kingdom.  Dr. Fonder, a graduate of and twice a fellowship recipient at the University of Illinois, was director of bands at Park Falls (Wisconsin) High School and was on the faculties of the University of Wisconsin-Green Bay and University of Texas-San Antonio prior to coming to New York.  He has also served on the faculties of The University of Washington, VanderCook College and the Eastman School of Music.  Dr. Fonder authored an award-winning book, Patrick Conway and his Famous Band (Meredith Publications, 2012) and his research (over 30 articles) has been published in various journals including the Music Educators Journal, Winds, Band Directors Guide, Instrumentalist, Journal of Band Research, Council for Research in Music Education and the Journal of Research in Music Education.  He was chair of the Music Educators Journal Editorial Committee from 1998-2002 and was the editor of the Journal of Historical Research in Music Education from 2003 to 2015.  He is currently on the editorial board of the Journal of Band Research.  Dr. Fonder has played principal trombone with the Green Bay (Wisconsin) Symphony, the Green Bay Packer Band, and the San Antonio Brass, and for such entertainers as Robert Goulet, Rich Little, and Rita Moreno.  In 1987, Dr. Fonder was awarded the National Band Association-Wisconsin Chapter Citation of Excellence, in 1998, the Ithaca College President's Recognition Award, in 2013, the Ithaca College Faculty Excellence Award, in 2015, the New York State Band Directors Association Band Director of the Year, and has been the recipient of a University of Wisconsin teaching fellowship.  He has been elected to Phi Delta Kappa, an honorary education fraternity, Phi Kappa Phi, an honorary scholars fraternity, Pi Kappa Lambda, an honorary music fraternity and the prestigious American Bandmasters Association.  In 2015, he moved back to his home state, Wisconsin, and is currently the conductor and artistic director of the Wisconsin Symphonic Winds."})

Interest.create([
  { user_id: 1, instrument_id: 2},
  { user_id: 2, instrument_id: 1},
  { user_id: 3, instrument_id: 1}, { user_id: 3, instrument_id: 2}, { user_id: 3, instrument_id: 3}, { user_id: 3, instrument_id: 4}, { user_id: 3, instrument_id: 5}, { user_id: 3, instrument_id: 6},
  { user_id: 3, instrument_id: 7}, { user_id: 3, instrument_id: 8}, { user_id: 3, instrument_id: 9}, { user_id: 3, instrument_id: 10}, { user_id: 3, instrument_id: 11}, { user_id: 3, instrument_id: 12},
  { user_id: 4, instrument_id: 4},
  { user_id: 5, instrument_id: 13}, { user_id: 5, instrument_id: 14}, { user_id: 5, instrument_id: 15},
  { user_id: 6, instrument_id: 4},
  { user_id: 7, instrument_id: 12},
  { user_id: 8, instrument_id: 2}, { user_id: 8, instrument_id: 16},
  { user_id: 9, instrument_id: 1}, { user_id: 9, instrument_id: 2}, { user_id: 9, instrument_id: 3}, { user_id: 9, instrument_id: 4}, { user_id: 9, instrument_id: 5}, { user_id: 9, instrument_id: 6},
  { user_id: 9, instrument_id: 7}, { user_id: 9, instrument_id: 8}, { user_id: 9, instrument_id: 9}, { user_id: 9, instrument_id: 10}, { user_id: 9, instrument_id: 11}, { user_id: 9, instrument_id: 12},
  { user_id: 9, instrument_id: 13}, { user_id: 9, instrument_id: 14}, { user_id: 9, instrument_id: 15}, { user_id: 9, instrument_id: 16},
  ])
